### ISSUE TITLE
Skin API Question

### ISSUE THREAD

**Issue by rabross** [Yive/MCAPI-Support#13]
**API**: Skin API
**Description**:

The Skin API takes a username to make a request.
Player data requests by username was officially deprecated by Mojang since UUIDs were introduced.
Do you make a request to get the UUID for the given username before making the request to get the skin?
I'm trying to gauge how reliable your service is.

**Language you're using**: English

**Comment by Yive** [comment]
Usernames weren't fully deprecated, there's a method I use which still accepts usernames over UUIDs. This method has been usable for well over 4 years now & I doubt it'll change anytime in the future. Even if it does, I cache the skins locally so that if something does happen, the service wont be 100% broken until I fix it to the new method, just will be broken to usernames that weren't cached.

I feel like that answer was longer than it needed to be, but note I will be adding UUID support by the end of this year along with a similar process to what you stated above about the grabbing the UUID of a specific username provided in the request.

**Comment by rabross** [comment]
Thanks for that Yive.
That all sounds good.
